image: node:6.5.0


cache:
  paths:
  - node_modules/

services:
  - mongo:latest
  
stages:
  - test
  - deploy

staging:
  stage: test
  image: ruby:latest
  script:
    - gem install dpl
    - dpl --provider=heroku --app=moovr-staging --api-key=$HEROKU_MOOVR_STAGING_API_KEY
  environment:
    name: development

production:
  stage: deploy
  image: ruby:latest
  script:
    - gem install dpl
    - dpl --provider=heroku --app=moovr-staging --api-key=$HEROKU_MOOVR_STAGING_API_KEY
  only:
    - master
